services:
  # PHP実行環境 (Laravel)
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=phper
      - DB_PASSWORD=password
      - MAIL_MAILER=smtp
      - MAIL_HOST=mail
      - MAIL_PORT=1025
    depends_on:
      - db

  # Webサーバー (Nginx) - ポートを8080に変更して衝突回避
  web:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

# データベース (MySQL 8.0)
  db:
    image: mysql:8.0.26
    platform: linux/amd64  # <--- この一行を必ず追加してください
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "33060:3306"
    volumes:
      - db-store:/var/lib/mysql

  # メールテスト用 (Mailpit) - 応用要件のメール認証で使用
  mail:
    image: axllent/mailpit
    ports:
      - "1025:1025" # SMTP (Laravelからの送信)
      - "8025:8025" # Web UI (ブラウザでメール確認)

volumes:
  db-store: